# Generated by Django 6.0.2 on 2026-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('yosh', models.SmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
